export const UPDATE_QUERY = 'UPDATE_QUERY';
export const FETCH_RESTAURANTS_START = 'FETCH_RESTAURANTS_START';
export const FETCH_RESTAURANTS_FINISH = 'FETCH_RESTAURANTS_FINISH';
export const TOGGLE_SELECTED = 'TOGGLE_SELECTED';
export const UPDATED_CHOSEN_RESTAURANT = 'UPDATE_CHOSEN_RESTAURANT';
